version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8

    environment:
      TZ: /usr/share/zoneinfo/America/Araguaina

    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Nodejs Version
          command: node --version

      - run: 
          name: Install Packages
          command: yarn install

      - run: 
          name: Running tests
          command: yarn test

      - save_cache:
          name: Save node_modules cache
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules